name: Run Python Script

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVERS: ${{ secrets.EMAIL_RECEIVERS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python 60_ripetute_camuffate.py

      - name: Push CSV to public output repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://x-access-token:${GH_PAT}@github.com/albagammamarketing-source/output-60_ripetute_camuffate.git output_repo

          cp output/*.csv output_repo/

          cd output_repo

          git add .

          git commit -m "Aggiornamento automatico CSV" || echo "Nessuna modifica da salvare"

          git push
